# General
name: Drematorium
description: "Test"
url: http://iltabiai.github.io

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: joydisee
github: joydisee
google: +joydisee

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
sass_dir: _sass
style: :compressed
