# General
name: iltabiai's blog
description: "Simple tricks and tips"
url: http://iltabiai.github.io

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: iltabiai
twitter: joydisee
github: joydisee
google: +IlyassT
rss: true
linkedin: ilyasstabiai

# RSS feed
rss-feed-limit: 10
rss-show-full: "yes"

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
sass_dir: _sass
style: :compressed
exclude: [Gemfile , README.md , LICENSE]
